ARG VERSION=latest

FROM ubuntu:$VERSION

RUN echo $VERSION > image_version

# Comment
RUN echo 'we are running ubuntu install'

# USER SETTING
USER rain2002kr

# WORKDIR SETTING
WORKDIR /app

RUN apt-get update

RUN apt-install node -y

CMD ["node-v"]

